apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-express-sqlserver
  namespace: default
spec:
  releaseName: node-express-sqlserver
  chart:
    spec:
      chart: ./node-express-sqlserver-chart
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
        namespace: flux-system
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: node-express-sqlserver-values
