apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-express-sqlserver
  namespace: default
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
        namespace: flux-system
      interval: 5m
      chart: node-express-sqlserver
      version: "1.0.0"
  values:
    image:
      repository: frnn4268/node-express-sqlserver
      tag: 1.0.0
    service:
      type: LoadBalancer
    sqlserver:
      sa_password: "my_sa_password"
      