apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: my-helm-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Frnn4268/gitops-node-sqlserver.git
